// network-flow.models.ts
// Matches Spring Boot DTOs exactly - field names follow Jackson camelCase serialization

export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
  timestamp: string;
}

// ── Gold table DTOs ───────────────────────────────────────────────────────

export interface NetworkFlowKpis {
  totalPairs: number;
  totalFlows: number;
  avgLatencyMs: number;
  p95LatencyMs: number;
  minLatencyMs: number;
  maxLatencyMs: number;
  avgHopCount: number;
  maxHopCount: number;
  healthyPairs: number;
  degradedPairs: number;
  criticalPairs: number;
}

export interface NetworkHubStat {
  hubNode: string;
  hubType: 'CORE_HUB' | 'MESH_NODE' | 'EDGE_NODE' | 'CUSTOMER_SITE' | 'TRANSIT';
  flowsThrough: number;
  avgPathLatencyMs: number;
  minPathLatencyMs: number;
  maxPathLatencyMs: number;
  avgHopCount: number;
}

export interface NetworkLinkLatency {
  circuitId: string;
  fromNode: string;
  toNode: string;
  measurementCount: number;
  avgLatencyMs: number;
  minLatencyMs: number;
  maxLatencyMs: number;
  p95LatencyMs: number;
  linkHealth: 'HEALTHY' | 'DEGRADED' | 'CRITICAL';
}

export interface NetworkPathStat {
  hopCount: number;
  flowCount: number;
  avgLatencyMs: number;
  minLatencyMs: number;
  maxLatencyMs: number;
  pctOfTotal: number;
  complexityLabel: 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
}

/**
 * NetworkFlowSummaryRow
 * One row from gold.network_flow_summary.
 * Returned by GET /api/network-flows/flow-summary
 * Contains actual customer site (DK_*) to hub (UURWMEA*) pairs.
 */
export interface NetworkFlowSummaryRow {
  sourceNode:   string;
  destNode:     string;
  flowCount:    number;
  avgLatencyMs: number;
  healthStatus: 'HEALTHY' | 'DEGRADED' | 'CRITICAL';
}

// ── Coordinate asset model ────────────────────────────────────────────────
// Loaded from src/assets/data/router-coordinates.json
// Generated by extract_coordinates.py from master_dataframe_long.xlsx

export interface RouterCoordinate {
  lat: number;
  lng: number;
}

export type RouterCoordinates = Record<string, RouterCoordinate>;

// ── D3 Hop Tree internal models ───────────────────────────────────────────

export interface HopTreeNode {
  name: string;
  nodeType: string;
  latency?: number;
  circuitId?: string;
  flowsThrough?: number;
  children: HopTreeNode[];
}

// ── Trail Map internal models ─────────────────────────────────────────────

export interface MapRoute {
  customerNode: string;
  hubNode: string;
  latencyMs: number;
  linkHealth: string;
  flowsThrough: number;
  hubLat: number;
  hubLng: number;
  customerLat: number;
  customerLng: number;
}

// ── Dataset / direction options ───────────────────────────────────────────

export type Dataset   = 'MEADE' | 'DAI' | 'ALL';
export type Direction = 'inbound' | 'outbound';