package mil.disa.oe.repository;

import mil.disa.oe.config.TableNames;
import mil.disa.oe.dto.*;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;

/** Source: NETCOOL (Network Event Management & Alerting) */
@Repository
public class TopIssuesRepository {

    private final NamedParameterJdbcTemplate jdbc;
    private final TableNames tables;

    public TopIssuesRepository(NamedParameterJdbcTemplate jdbc, TableNames tables) {
        this.jdbc   = jdbc;
        this.tables = tables;
    }

    // ── Hive JDBC compatibility helpers ───────────────────────────────────
    //
    // 1. DOUBLE columns: Hive returns java.lang.Double, not BigDecimal.
    //    Fix: bd() reads via getDouble() and wraps in BigDecimal.valueOf().
    //
    // 2. NULL aggregates: SQL COUNT/AVG return NULL when 0 rows match.
    //    Fix: safeInt() returns 0 for null values.
    //
    // 3. TIMESTAMP columns: Hive stores timestamps as strings internally.
    //    rs.getTimestamp() throws "Illegal conversion".
    //    Fix: ts() reads as String and parses to LocalDateTime.

    private static BigDecimal bd(ResultSet rs, String col) throws SQLException {
        double v = rs.getDouble(col);
        return rs.wasNull() ? null : BigDecimal.valueOf(v);
    }

    private static BigDecimal bd(Object val) {
        if (val == null) return null;
        if (val instanceof BigDecimal b) return b;
        return BigDecimal.valueOf(((Number) val).doubleValue());
    }

    private static int safeInt(Object val) {
        return val == null ? 0 : ((Number) val).intValue();
    }

    private static LocalDateTime ts(ResultSet rs, String col) throws SQLException {
        String s = rs.getString(col);
        if (s == null || s.isBlank()) return null;
        try {
            return LocalDateTime.parse(s.replace(" ", "T")
                                        .replaceAll("\\.\\d+$", ""));
        } catch (Exception e) {
            return null;
        }
    }

    @Retryable(retryFor = Exception.class, maxAttempts = 3,
               backoff = @Backoff(delay = 2000, multiplier = 2.0))
    public IssuesKpis getKpis() {
        String kpiSql = """
            SELECT
                COUNT(CASE WHEN severity='P1' AND status!='RESOLVED' THEN 1 END) AS p1_open,
                COUNT(CASE WHEN severity='P2' AND status!='RESOLVED' THEN 1 END) AS p2_open,
                COUNT(CASE WHEN severity='P3' AND status!='RESOLVED' THEN 1 END) AS p3_open,
                COUNT(CASE WHEN severity='P4' AND status!='RESOLVED' THEN 1 END) AS p4_open,
                COUNT(CASE WHEN status != 'RESOLVED'                 THEN 1 END) AS total_open,
                COUNT(CASE WHEN status = 'RESOLVED'
                            AND DATE(resolved_at) = current_date()   THEN 1 END) AS resolved_today,
                ROUND(AVG(CASE WHEN status='RESOLVED'
                          THEN mttr_minutes END) / 60.0, 1)                      AS avg_mttr_hours,
                ROUND(COUNT(CASE WHEN sla_breached = true THEN 1 END)
                      * 100.0 / NULLIF(COUNT(*),0), 1)                           AS sla_breach_rate
            FROM %s
            WHERE opened_at >= current_date() - 30
            """.formatted(tables.topIssuesSummary());

        String byCatSql = """
            SELECT category,
                   COUNT(CASE WHEN status != 'RESOLVED' THEN 1 END) AS open_count,
                   COUNT(CASE WHEN status = 'RESOLVED'  THEN 1 END) AS resolved_count,
                   ROUND(AVG(CASE WHEN status='RESOLVED'
                             THEN mttr_minutes END) / 60.0, 1)       AS avg_mttr
            FROM %s
            WHERE opened_at >= current_date() - 30
            GROUP BY category
            ORDER BY open_count DESC
            """.formatted(tables.topIssuesSummary());

        // ── Trending Issues ───────────────────────────────────────────────
        // gold.issue_trends is not generated by the current pipeline.
        // Derived from top_issues_summary as a proxy: recurring issues by category.
        String trendingSql = """
            SELECT category                               AS pattern,
                   COUNT(*)                               AS occurrences,
                   category                               AS affected_component,
                   CASE WHEN COUNT(*) > 50 THEN 'INCREASING'
                        WHEN COUNT(*) > 20 THEN 'STABLE'
                        ELSE 'DECREASING'
                   END                                    AS trend
            FROM %s
            WHERE opened_at >= current_date() - 30
              AND is_recurring = true
            GROUP BY category
            ORDER BY occurrences DESC
            LIMIT 5
            """.formatted(tables.topIssuesSummary());

        String criticalSql = """
            SELECT issue_id, title, category, severity, status, source,
                   affected_devices, affected_users, opened_at, last_updated_at,
                   resolved_at, mttr_minutes, assigned_team, root_cause,
                   is_recurring, occurrence_count
            FROM %s
            WHERE severity IN ('P1','P2')
              AND status != 'RESOLVED'
            ORDER BY severity, opened_at ASC
            LIMIT 10
            """.formatted(tables.topIssuesSummary());

        var r = jdbc.queryForMap(kpiSql, Collections.emptyMap());

        List<IssuesByCategory> byCat = jdbc.query(byCatSql,
            Collections.emptyMap(), (rs, i) -> new IssuesByCategory(
                rs.getString("category"), rs.getInt("open_count"),
                rs.getInt("resolved_count"), bd(rs, "avg_mttr")));

        List<TrendingIssue> trending = jdbc.query(trendingSql,
            Collections.emptyMap(), (rs, i) -> new TrendingIssue(
                rs.getString("pattern"), rs.getInt("occurrences"),
                rs.getString("affected_component"), rs.getString("trend")));

        List<TopIssueSummary> critical = jdbc.query(criticalSql,
            Collections.emptyMap(), (rs, i) -> new TopIssueSummary(
                rs.getString("issue_id"), rs.getString("title"),
                rs.getString("category"), rs.getString("severity"),
                rs.getString("status"), rs.getString("source"),
                rs.getInt("affected_devices"), rs.getInt("affected_users"),
                ts(rs, "opened_at"),           // ← was rs.getTimestamp().toLocalDateTime()
                ts(rs, "last_updated_at"),     // ← was rs.getTimestamp().toLocalDateTime()
                ts(rs, "resolved_at"),         // ← was rs.getTimestamp() != null ? ...
                rs.getLong("mttr_minutes"), rs.getString("assigned_team"),
                rs.getString("root_cause"), rs.getBoolean("is_recurring"),
                rs.getInt("occurrence_count")));

        return new IssuesKpis(
            safeInt(r.get("p1_open")),         // ← was ((Number) r.get(...)).intValue()
            safeInt(r.get("p2_open")),
            safeInt(r.get("p3_open")),
            safeInt(r.get("p4_open")),
            safeInt(r.get("total_open")),
            safeInt(r.get("resolved_today")),
            bd(r.get("avg_mttr_hours")),
            bd(r.get("sla_breach_rate")),
            byCat, trending, critical);
    }
}